---
version: 2

plugins:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
  markdownlint:
    enabled: true
  radon:
    enabled: true

checks:
  argument-count:
    config:
      threshold: 4
  complex-logic:
    config:
      threshold: 4
  file-lines:
    config:
      threshold: 500
  method-complexity:
    config:
      threshold: 15
  method-count:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 50

exclude_patterns:
  - "**/node_modules/**/*"
  - "**/out/**/*"
  - "**/dist/**/*"
  - "**/.vscode/**/*"
  - "**/.vscode-test/**/*"
  - "client/server/**/*"
  - "**/.git/**/*"
  - "**/webpack.config.js"
  - "**/tsconfig.json"
  - "**/customInstallServerIntoExtension.js"
  - "**/tsconfig.base.json"
  - "**/shared.webpack.config.js"

